const SUPABASE_URL = "'https://nxdyelrocjkypboayeoy.supabase.co'";
const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im54ZHllbHJvY2preXBib2F5ZW95Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk3NjM1NzksImV4cCI6MjA1NTMzOTU3OX0.C3JnxBLQf9YDI7CfMYRt4VM9QZZZiKnH0xrJ9dW9RFY";

const supabase = supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
